### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by swills** [basecode-lang/bootstrap#1]
I'm trying to build and getting this error:

https://gist.github.com/swills/c0b2852bafb507c4b06c71eb19d81f94

only thing I can find related is:

https://svn.boost.org/trac10/ticket/1011

but that's quite old. I am building on FreeBSD 12-CURRENT using clang 6.0.1. What am I missing?

**Comment by jeffpanici75** [comment]
I fixed the build, at least temporarily, so that it works under FreeBSD 12-CURRENT.  Since I'm building some of the boost libraries outside of bjam, I think some definitions are missing.  Temporarily I'm adding __USE_ISOC99 which fixes the build issue with boost.  I also add the PIC flag.
